bash:
  project: Wafer-quality-project
  random_state: 44
  target_col: Output


data_source:
  batch_files: Training_Batch_Files

data_preparation:
  training_db: Training.db
  training_db_dir: Training_Database
  schema_training: config/schema_training.json
  good_validation_raw_dir: data/Training_Raw_files_validated/Good_raw
  bad_validation_raw_dir: data/Training_Raw_files_validated/Bad_raw
  TrainingArchiveBadData: data/TrainingArchiveBadData
  Training_FileFromDB: data/Training_FileFromDB
  master_csv: master.csv